export const AUCTION_SETTINGS = {
  purse: 10000,
  entryFee: 2500,
  minPlayers: 11,
  maxPlayers: 15,
  minBidStepLakh: 5,
  payoutSplit: [4, 3, 2, 1],
  scoringSystem: "Fantasy IPL T20",
  winnerBasis: "Highest total points at tournament end",
};

export const AUCTION_RULES = [
  "Each owner will get 100 cr in their purse.",
  "You have to make a team of minimum 11, maximum 15 players.",
  "There is no cap on how many players you can take from an IPL team.",
  "There is no cap on any specialisation, batting, bowling or keepers.",
  "Scoring of players will be done as per the Fantasy IPL T20 scoring rules.",
  "Each owner will get points of all the players in his team. You do not have to select a playing 11.",
  "At the end of the tournament, the owner with the highest points wins.",
  "Winning split is in the ratio of 4:3:2:1.",
  "There is a one time entry fee of 2500₹ paid upfront.",
  "This is a one time event. There are no transfers, no captains, and no overheads after the auction is done.",
  "If a player gets injured, you will get the official replacement from that IPL franchise. No player from the remaining player pool can be allotted.",
  "No players can be exchanged between owners.",
  "I will post the updated league standing of owners once every 2-3 days.",
  "Players will get points till the end of the tournament, so players from franchises that reach the knockout stage can earn more points.",
  "I will share the database of players beforehand. Players will be divided into categories A, B, C and D, based on their past performance and vibe.",
];

const TEAM_BLOCKS = [
  {
    team: "Chennai Super Kings",
    players: [
      ["Anshul Kamboj", 340],
      ["Gurjapneet Singh", 220],
      ["Jamie Overton", 150, true],
      ["MS Dhoni", 400],
      ["Mukesh Choudhary", 30],
      ["Nathan Ellis", 200, true],
      ["Noor Ahmad", 1000, true],
      ["Ramakrishna Ghosh", 30],
      ["Sanju Samson (T)", 1800],
      ["Ruturaj Gaikwad", 1800],
      ["Shivam Dube", 1200],
      ["Shreyas Gopal", 30],
      ["Syed Khaleel Ahmed", 480],
      ["Ayush Mhatre", 30],
      ["Dewald Brevis", 220, true],
      ["Urvil Patel", 30],
    ],
  },
  {
    team: "Delhi Capitals",
    players: [
      ["Abhishek Porel", 400],
      ["Ajay Mandal", 30],
      ["Ashutosh Sharma", 380],
      ["Axar Patel", 1650],
      ["Dushmantha Chameera", 75, true],
      ["Karun Nair", 50],
      ["KL Rahul", 1400],
      ["Kuldeep Yadav", 1325],
      ["Madhav Tiwari", 40],
      ["Mitchell Starc", 1175, true],
      ["Mukesh Kumar", 800],
      ["Nitish Rana (T)", 420],
      ["Sameer Rizvi", 95],
      ["T. Natarajan", 1075],
      ["Tripurana Vijay", 30],
      ["Tristan Stubbs", 1000, true],
      ["Vipraj Nigam", 50],
    ],
  },
  {
    team: "Gujarat Titans",
    players: [
      ["Anuj Rawat", 30],
      ["Glenn Phillips", 200, true],
      ["Gurnoor Singh Brar", 130],
      ["Ishant Sharma", 75],
      ["Jayant Yadav", 75],
      ["Jos Buttler", 1575, true],
      ["Kagiso Rabada", 1075, true],
      ["Kumar Kushagra", 65],
      ["Manav Suthar", 30],
      ["Mohammad Siraj", 1225],
      ["Mohd. Arshad Khan", 130],
      ["Nishant Sindhu", 30],
      ["Prasidh Krishna", 950],
      ["R. Sai Kishore", 200],
      ["Rahul Tewatia", 400],
      ["Rashid Khan", 1800, true],
      ["Sai Sudharsan", 850],
      ["Shahrukh Khan", 400],
      ["Shubman Gill", 1650],
      ["Washington Sundar", 320],
    ],
  },
  {
    team: "Kolkata Knight Riders",
    players: [
      ["Ajinkya Rahane", 150],
      ["Angkrish Raghuvanshi", 300],
      ["Anukul Roy", 40],
      ["Harshit Rana", 400],
      ["Manish Pandey", 75],
      ["Ramandeep Singh", 400],
      ["Rinku Singh", 1300],
      ["Rovman Powell", 150, true],
      ["Sunil Narine", 1200, true],
      ["Umran Malik", 75],
      ["Vaibhav Arora", 180],
      ["Varun Chakaravarthy", 1200],
    ],
  },
  {
    team: "Lucknow Super Giants",
    players: [
      ["Abdul Samad", 420],
      ["Aiden Markram", 200, true],
      ["Akash Singh", 30],
      ["Arjun Tendulkar (T)", 30],
      ["Arshin Kulkarni", 30],
      ["Avesh Khan", 975],
      ["Ayush Badoni", 400],
      ["Digvesh Rathi", 30],
      ["Himmat Singh", 30],
      ["Manimaran Siddharth", 75],
      ["Matthew Breetzke", 75, true],
      ["Mayank Yadav", 1100],
      ["Md Shami (T)", 1000],
      ["Mitchell Marsh", 340, true],
      ["Mohsin Khan", 400],
      ["Nicholas Pooran", 2100, true],
      ["Prince Yadav", 30],
      ["Rishabh Pant", 2700],
      ["Shahbaz Ahmed", 240],
    ],
  },
  {
    team: "Mumbai Indians",
    players: [
      ["Allah Ghazanfar", 480, true],
      ["Ashwani Kumar", 30],
      ["Corbin Bosch", 75, true],
      ["Deepak Chahar", 925],
      ["Hardik Pandya", 1635],
      ["Jasprit Bumrah", 1800],
      ["Mayank Markande (T)", 30],
      ["Mitchell Santner", 200, true],
      ["Naman Dhir", 525],
      ["Raghu Sharma", 30],
      ["Raj Angad Bawa", 30],
      ["Robin Minz", 65],
      ["Rohit Sharma", 1630],
      ["Ryan Rickelton", 100, true],
      ["Shardul Thakur (T)", 200],
      ["Sherfane Rutherford (T)", 260, true],
      ["Suryakumar Yadav", 1635],
      ["Tilak Verma", 800],
      ["Trent Boult", 1250, true],
      ["Will Jacks", 525, true],
    ],
  },
  {
    team: "Punjab Kings",
    players: [
      ["Arshdeep Singh", 1800],
      ["Azmatullah Omarzai", 240, true],
      ["Harnoor Pannu", 30],
      ["Harpreet Brar", 150],
      ["Lockie Ferguson", 200, true],
      ["Marco Jansen", 700, true],
      ["Marcus Stoinis", 1100, true],
      ["Mitch Owen", 300, true],
      ["Musheer Khan", 30],
      ["Nehal Wadhera", 420],
      ["Prabhsimran Singh", 400],
      ["Priyansh Arya", 380],
      ["Pyla Avinash", 30],
      ["Shashank Singh", 550],
      ["Shreyas Iyer", 2675],
      ["Suryansh Shedge", 30],
      ["Vishnu Vinod", 95],
      ["Vyshak Vijaykumar", 180],
      ["Xavier Bartlett", 80, true],
      ["Yash Thakur", 160],
      ["Yuzvendra Chahal", 1800],
    ],
  },
  {
    team: "Rajasthan Royals",
    players: [
      ["Dhruv Jurel", 1400],
      ["Donovan Ferreira (T)", 100, true],
      ["Jofra Archer", 1250, true],
      ["Kwena Maphaka", 150, true],
      ["Lhuan-Dre Pretorious", 30, true],
      ["Nandre Burger", 350, true],
      ["Ravindra Jadeja (T)", 1400],
      ["Riyan Parag", 1400],
      ["Sam Curran (T)", 240, true],
      ["Sandeep Sharma", 400],
      ["Shimron Hetmyer", 1100, true],
      ["Shubham Dubey", 80],
      ["Tushar Deshpande", 650],
      ["Vaibhav Suryavanshi", 110],
      ["Yashaswi Jaiswal", 1800],
      ["Yudhvir Charak", 35],
    ],
  },
  {
    team: "Royal Challengers Bengaluru",
    players: [
      ["Abhinandan Singh", 30],
      ["Bhuvneshwar Kumar", 1075],
      ["Devdutt Padikkal", 200],
      ["Jacob Bethell", 260, true],
      ["Jitesh Sharma", 1100],
      ["Josh Hazlewood", 1250, true],
      ["Krunal Pandya", 575],
      ["Nuwan Thushara", 160, true],
      ["Phil Salt", 1150, true],
      ["Rajat Patidar", 1100],
      ["Rasikh Dar", 600],
      ["Romario Shepherd", 150, true],
      ["Suyash Sharma", 260],
      ["Swapnil Singh", 50],
      ["Tim David", 300, true],
      ["Virat Kohli", 2100],
      ["Yash Dayal", 500],
    ],
  },
  {
    team: "Sunrisers Hyderabad",
    players: [
      ["Abhishek Sharma", 1400],
      ["Aniket Verma", 30],
      ["Brydon Carse", 100, true],
      ["Eshan Malinga", 120, true],
      ["Harsh Dubey", 30],
      ["Harshal Patel", 800],
      ["Heinrich Klaasen", 2300, true],
      ["Ishan Kishan", 1125],
      ["Jaydev Unadkat", 100],
      ["Kamindu Mendis", 75, true],
      ["Nitish Kumar Reddy", 600],
      ["Pat Cummins", 1800, true],
      ["Smaran Ravichandaran", 30],
      ["Travis Head", 1400, true],
      ["Zeeshan Ansari", 40],
    ],
  },
];

function slugify(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

function deriveCategory(costLakh) {
  if (costLakh >= 1500) return "A";
  if (costLakh >= 800) return "B";
  if (costLakh >= 200) return "C";
  return "D";
}

export const PLAYER_POOL = TEAM_BLOCKS.flatMap((block) =>
  block.players.map(([name, baseCostLakh, overseas = false], index) => ({
    id: `${slugify(block.team)}-${index + 1}`,
    name,
    team: block.team,
    category: deriveCategory(baseCostLakh),
    cost: baseCostLakh,
    baseCostLakh,
    overseas,
  })),
);
